"""ITB — Python binding over libitb shared library.

The package wraps the C ABI exported by cmd/cshared (libitb.so / .dll /
.dylib) through ``cffi`` in ABI mode (no compile step on install). The
public surface is intentionally narrow:

    >>> import itb
    >>> seeds = [itb.Seed("blake3", 1024) for _ in range(3)]
    >>> ct = itb.encrypt(*seeds, b"hello world")
    >>> pt = itb.decrypt(*seeds, ct)
    >>> assert pt == b"hello world"

Authenticated variants take an additional MAC handle:

    >>> mac = itb.MAC("hmac-sha256", os.urandom(32))
    >>> ct = itb.encrypt_auth(*seeds, mac, b"integrity-protected")
    >>> pt = itb.decrypt_auth(*seeds, mac, ct)

Hash names match the canonical FFI registry (see hashes/registry.go):
``areion256``, ``areion512``, ``siphash24``, ``aescmac``, ``blake2b256``,
``blake2b512``, ``blake2s``, ``blake3``, ``chacha20``.

MAC names: ``kmac256``, ``hmac-sha256``, ``hmac-blake3``.
"""

from ._ffi import (
    Seed,
    MAC,
    encrypt,
    decrypt,
    encrypt_triple,
    decrypt_triple,
    encrypt_auth,
    decrypt_auth,
    encrypt_auth_triple,
    decrypt_auth_triple,
    list_hashes,
    list_macs,
    version,
    set_bit_soup,
    set_lock_soup,
    set_max_workers,
    set_nonce_bits,
    set_barrier_fill,
    get_bit_soup,
    get_lock_soup,
    get_max_workers,
    get_nonce_bits,
    get_barrier_fill,
    max_key_bits,
    channels,
    header_size,
    parse_chunk_len,
    last_error,
    ITBError,
    ItbStreamTruncatedError,
    ItbStreamAfterFinalError,
    STATUS_OK,
    STATUS_BAD_HASH,
    STATUS_BAD_KEY_BITS,
    STATUS_BAD_HANDLE,
    STATUS_BAD_INPUT,
    STATUS_BUFFER_TOO_SMALL,
    STATUS_ENCRYPT_FAILED,
    STATUS_DECRYPT_FAILED,
    STATUS_SEED_WIDTH_MIX,
    STATUS_BAD_MAC,
    STATUS_MAC_FAILURE,
    STATUS_EASY_CLOSED,
    STATUS_EASY_MALFORMED,
    STATUS_EASY_VERSION_TOO_NEW,
    STATUS_EASY_UNKNOWN_PRIMITIVE,
    STATUS_EASY_UNKNOWN_MAC,
    STATUS_EASY_BAD_KEY_BITS,
    STATUS_EASY_MISMATCH,
    STATUS_EASY_LOCKSEED_AFTER_ENCRYPT,
    STATUS_BLOB_MODE_MISMATCH,
    STATUS_BLOB_MALFORMED,
    STATUS_BLOB_VERSION_TOO_NEW,
    STATUS_BLOB_TOO_MANY_OPTS,
    STATUS_STREAM_TRUNCATED,
    STATUS_STREAM_AFTER_FINAL,
    STATUS_INTERNAL,
)
from .streams import (
    StreamEncryptor,
    StreamDecryptor,
    StreamEncryptor3,
    StreamDecryptor3,
    StreamEncryptorAuth,
    StreamDecryptorAuth,
    StreamEncryptorAuth3,
    StreamDecryptorAuth3,
    encrypt_stream,
    decrypt_stream,
    encrypt_stream_triple,
    decrypt_stream_triple,
    encrypt_stream_auth,
    decrypt_stream_auth,
    encrypt_stream_auth_triple,
    decrypt_stream_auth_triple,
    DEFAULT_CHUNK_SIZE,
)
from .easy import (
    Encryptor,
    EasyMismatchError,
    peek_config,
    last_mismatch_field,
)
from .blob import (
    Blob128,
    Blob256,
    Blob512,
    BlobModeMismatchError,
    BlobMalformedError,
    BlobVersionTooNewError,
    SLOT_N,
    SLOT_D,
    SLOT_S,
    SLOT_L,
    SLOT_D1,
    SLOT_D2,
    SLOT_D3,
    SLOT_S1,
    SLOT_S2,
    SLOT_S3,
    OPT_LOCKSEED,
    OPT_MAC,
)

__all__ = [
    "Seed",
    "MAC",
    "encrypt",
    "decrypt",
    "encrypt_triple",
    "decrypt_triple",
    "encrypt_auth",
    "decrypt_auth",
    "encrypt_auth_triple",
    "decrypt_auth_triple",
    "StreamEncryptor",
    "StreamDecryptor",
    "StreamEncryptor3",
    "StreamDecryptor3",
    "StreamEncryptorAuth",
    "StreamDecryptorAuth",
    "StreamEncryptorAuth3",
    "StreamDecryptorAuth3",
    "encrypt_stream",
    "decrypt_stream",
    "encrypt_stream_triple",
    "decrypt_stream_triple",
    "encrypt_stream_auth",
    "decrypt_stream_auth",
    "encrypt_stream_auth_triple",
    "decrypt_stream_auth_triple",
    "DEFAULT_CHUNK_SIZE",
    "list_hashes",
    "list_macs",
    "version",
    "set_bit_soup",
    "set_lock_soup",
    "set_max_workers",
    "set_nonce_bits",
    "set_barrier_fill",
    "get_bit_soup",
    "get_lock_soup",
    "get_max_workers",
    "get_nonce_bits",
    "get_barrier_fill",
    "max_key_bits",
    "channels",
    "header_size",
    "parse_chunk_len",
    "last_error",
    "ITBError",
    "ItbStreamTruncatedError",
    "ItbStreamAfterFinalError",
    "Encryptor",
    "EasyMismatchError",
    "peek_config",
    "last_mismatch_field",
    "Blob128",
    "Blob256",
    "Blob512",
    "BlobModeMismatchError",
    "BlobMalformedError",
    "BlobVersionTooNewError",
    "SLOT_N",
    "SLOT_D",
    "SLOT_S",
    "SLOT_L",
    "SLOT_D1",
    "SLOT_D2",
    "SLOT_D3",
    "SLOT_S1",
    "SLOT_S2",
    "SLOT_S3",
    "OPT_LOCKSEED",
    "OPT_MAC",
    "STATUS_OK",
    "STATUS_BAD_HASH",
    "STATUS_BAD_KEY_BITS",
    "STATUS_BAD_HANDLE",
    "STATUS_BAD_INPUT",
    "STATUS_BUFFER_TOO_SMALL",
    "STATUS_ENCRYPT_FAILED",
    "STATUS_DECRYPT_FAILED",
    "STATUS_SEED_WIDTH_MIX",
    "STATUS_BAD_MAC",
    "STATUS_MAC_FAILURE",
    "STATUS_EASY_CLOSED",
    "STATUS_EASY_MALFORMED",
    "STATUS_EASY_VERSION_TOO_NEW",
    "STATUS_EASY_UNKNOWN_PRIMITIVE",
    "STATUS_EASY_UNKNOWN_MAC",
    "STATUS_EASY_BAD_KEY_BITS",
    "STATUS_EASY_MISMATCH",
    "STATUS_EASY_LOCKSEED_AFTER_ENCRYPT",
    "STATUS_BLOB_MODE_MISMATCH",
    "STATUS_BLOB_MALFORMED",
    "STATUS_BLOB_VERSION_TOO_NEW",
    "STATUS_BLOB_TOO_MANY_OPTS",
    "STATUS_STREAM_TRUNCATED",
    "STATUS_STREAM_AFTER_FINAL",
    "STATUS_INTERNAL",
]
